name        'puppet-sabnzbd'
version     '0.0.1'
source      'git://github.com/liamjbennett/puppet-sabnzbd.git'
author      'Liam Bennett'
summary     'Module for installing sabnzbd newsreader'
description 'Install sabnzd, configure your indexes and start downloading nzbs'
license     'Apache License, Version 2.0'
dependency  'puppetlabs/git', '> 0'
dependency  'plathrop/puppet-module-supervisor', '> 0'
dependency  'camptocamp/puppet-python', git => 'https://github.com/camptocamp/puppet-python.git'
