name        'tomo0-sabnzbd'
version     '0.0.1'
source      'https://github.com/tomo0/puppet-sabnzbd.git'
author      'Tom Robinson'
summary     'Module for installing sabnzbd newsreader'
description 'Install sabnzd, configure your indexes and start downloading nzbs'
license     'Apache License, Version 2.0' '>0.0.0'
dependency 'stankevich/python', '1.2.1'
dependency 'rodjek/logrotate', '1.1.1'
dependency 'guilhermef/supervisor', '0.0.5'
dependency 'puppetlabs/vcsrepo', '0.2.0'
dependency 'puppetlabs/stdlib', '4.1.0'
